### ISSUE TITLE
Interface for mobile

### ISSUE THREAD

**Issue by evajurman** [ethanjurman/shoot-it#12]
Mobile interface shouldn't suck.
Easy to fire (make the whole screen a button).
Show score and color.
Calibration on a separate webpage.
Since we will most likely get devices to calibrate before hand, make it an option that people will not mistakenly get into (separate page)

**Comment by evajurman** [comment]
FULLSCREEN STUFF http://www.html5rocks.com/en/mobile/fullscreen/

**Comment by weswigham** [comment]
I'm pretty sure this is complete
