### ISSUE TITLE
gameplay features

### ISSUE THREAD

**Issue by evajurman** [ethanjurman/shoot-it#15]
- players can join at any time
- 30 seconds between rounds (shows qr code, players can join in, etc.)
- 5 different rounds per game, that are 2-3 minutes.
- Last round in a set is a boss.
- Rounds are randomly generated
- At the end of a set (or when a player leaves), scores are put into the highscore table, and reset.
- Special drones w/ power ups (health, shields, rapid fire, etc...).

**Comment by weswigham** [comment]
Each of these should be their own issue and this compilation a milestone.
