### ISSUE TITLE
Game States

### ISSUE THREAD

**Issue by evajurman** [ethanjurman/shoot-it#16]
Have a easy to use, game state changer.
Should only have to exist in the host device (I believe...).
![image](https://cloud.githubusercontent.com/assets/1131494/6666062/f0946f70-cbb6-11e4-894f-79eade10147c.png)

**Comment by evajurman** [comment]
@Rek3650 should this work okay? I'm trying to remember what we discussed the other day.

**Comment by Rek3650** [comment]
:+1:

**Comment by weswigham** [comment]
inbetween-> title screen, inbetween queue -> lobby

Because I'm pretty sure those are the canonical terms for those things.

**Comment by weswigham** [comment]
We have some stateish thing now - we could formalize it more, but the system we have now works.
