### ISSUE TITLE
Game Loop

### ISSUE THREAD

**Issue by evajurman** [ethanjurman/shoot-it#17]
The game loop should only have to exist in host/index.js...
Change the appropriate calls from event driven to inside the loop. (fire, add player, update player, etc. etc...)
i.e.

``` javascript
socket.on('update plane', function(p){
    updatePlane(p[0],p[1]); // playerId and motion
});
```

to

``` javascript
var players = {} // hash of players
socket.on('update plane', function(p){
    players[p[0]] = p[1]; // playerId and motion
});
// inside game loop
for (p in players) {
    updatePlane(p, players[p]); // playerId and motion
}
```

EDIT: Apparently you cannot assign two people to a single issue... which makes sense

**Comment by weswigham** [comment]
Correction: The only real game loop is in host/game/game.js (the
requestAnimationFrame render loop), and all other entities rely on it as it
is the render loop. This is just a matter of moving functionality in
host/index.js to host/game/entities/player.js to clean up the code. I
recommended that the socket events be attached in their own file, for
clarity, calling functions on the player store to look up a player, then
calling methods on the player object itself to perform the actions.

**Comment by evajurman** [comment]
So should the motion be stored in the player-store or inside the player object?
And the should logic be placed in requestAnimationFrame before self.render(), or before the recursive call (after the reference to self)?

**Comment by weswigham** [comment]
Motion and motion control are the motion of the player entity respectfully, so should be stored as instance members of a player entity. This makes sense, right? 

This would make the socket listener look more like:

``` js
socket.on('update plane', function(p){
    var ply = players.find(p[0]);
    if (!ply) throw Error('received update for nonexistent player!');
    ply.setMotion(p[1]);
});
```

The player store is merely how the event listeners can lookup the correct player instance/add a new player instance/remove a player instance.

The render loop call looks recursive, but it's not. It's delayed by the requestAnimationFrame system call.

**Comment by weswigham** [comment]
Pretty sure this is solidly done
